version: '3'
services:
  db:
    image: postgres
    volumes:
    - ./tmp/shared/postgresql:/var/lib/postgresql/data
    - ./tmp/shared/dumps:/shared_dumps
    ports:
    - 5432:5432
    env_file:
    - config/docker.env
  web:
    build: .
    command:
      - ./run.sh
    volumes:
    - .:/myapp
    ports:
    - "80:4000"
    env_file:
    - config/docker.env
    depends_on:
    - db